export const HELPER = [
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.ADD_NODE.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.ADD_NODE.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.ADD_EDGE.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.ADD_EDGE.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.EDIT_EDGE.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.EDIT_EDGE.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.DELETE.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.DELETE.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.FILES.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.FILES.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.SAVE.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.SAVE.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.NEW.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.NEW.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.REPRESENTATIONS.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.REPRESENTATIONS.LABEL'
    },
    {
        key: 'EDITOR.NAVIGATION.KEYBOARD.ALGORITHMS.KEY',
        label: 'EDITOR.NAVIGATION.KEYBOARD.ALGORITHMS.LABEL'
    }
];